#%RAML 1.0 NamedExample
value:

  -
    AvionID: 1
    Model: "Boing 747"
    BrojLeta: "MUN703"
    PutniciEconomy: 103
    PutniciBusiness: 50
    BrojClanovaPosade: 20
    Vlasnik: "Turkish Airlines"
  -
    AvionID: 2
    Model: "Boing 737"
    BrojLeta: "BER533"
    PutniciEconomy: 123
    PutniciBusiness: 47
    BrojClanovaPosade: 22
    Vlasnik: "Etihad Airlines"
