#%RAML 1.0 DataType

type: object
properties:
  PutnikID?: integer
  Ime?: string
  Prezime?: string
  BrojTel?: string
  EMail?: string
  Godine?: integer
  JMBG: string
  prtljag:
    type: object
    required: false
    properties:
      PrtljagID?: integer
      RucniPrtljag: boolean
      Tezina: integer
      PredjenaKontrola: boolean
      SifraPrtljag: string
  pasos:
    type: object
    required: false
    properties:
      PasosID?: integer
      Viza: boolean
      Ime?: string
      Drzava: string
      Prezime?: string
      Godine: integer
  karta:
    type: object
    required: false
    properties:
      KartaID?: integer
      CenaKarte?: integer
      BrojKredKartice?: string
      Klasa?: string
      Sediste?: integer
      SifraKarte: string
      let:
        type: object
        required: false
        properties:
          LetID?: integer
          NazivLinije?: string
          SifraLeta: string
          avion:
            type: object
            required: false
            properties:
              AvionID?: integer
              Model?: string
              BrojLeta: string
              PutniciEconomy?: integer
              PutniciBusiness?: integer
              BrojClanovaPosade?: integer
              Vlasnik?: string
          poletanje:
            type: object
            required: false
            properties:
              PoletanjeID?: integer
              Grad: string
              Datum: string
              Gate: string
          sletanje:
            type: object
            required: false
            properties:
              SletanjeID?: integer
              Grad: string
              Datum: string
              Gate: string