#%RAML 1.0 NamedExample
value:
  -
    PrtljagID: 1
    RucniPrtljag: false
    Tezina: 19
    PredjenaKontrola: true
    SifraPrtljag: "AEF23"
  -
    PrtljagID: 2
    RucniPrtljag: false
    Tezina: 18
    PredjenaKontrola: true
    SifraPrtljag: "GEF87"