#%RAML 1.0 NamedExample
value:
  -
    PasosID: 1
    Viza: true
    Ime: "Gojko"
    Drzava: "Srbija"
    Prezime: "Zemunac"
    Godine: 47
  -
    PasosID: 2
    Viza: false
    Ime: "Sofronije"
    Drzava: "Bugarska"
    Prezime: "Aziv"
    Godine: 32
