#%RAML 1.0 NamedExample
value:
    Ime: "Gojko"
    Prezime: "Zemunac"
    BrojTel: "0695548874"
    EMail: "gojkomunzekonza@gmail.com"
    Godine: 47
    JMBG: "300182957237391"
    prtljag:
      PrtljagID: 1
      RucniPrtljag: false
      Tezina: 19
      PredjenaKontrola: true
      SifraPrtljag: "AEF23"
    pasos:
      PasosID: 1
      
      Viza: true
      Ime: "Gojko"
      Drzava: "Srbija"
      Prezime: "Zemunac"
      Godine: 47
    karta:
      KartaID: 1
      CenaKarte: 130
      BrojKredKartice: "8398938457684728"
      Klasa: "Economy"
      Sediste: 33
      SifraKarte: "SFT484"
      let:
        LetID: 1
        NazivLinije: "MUNPAR332"
        SifraLeta: "54729232"
        avion:
          AvionID: 1
          Model: "Boing 747"
          BrojLeta: "MUN703"
          PutniciEconomy: 103
          PutniciBusiness: 50
          BrojClanovaPosade: 20
          Vlasnik: "Turkish Airlines"
        poletanje:
          PoletanjeID: 1
          Grad: "Minhen"
          Datum: "30-05-2023"
          Gate: "L7"
        sletanje:
          SletanjeID: 1
          Grad: "Paris"
          Datum: "30-05-2023"
          Gate: "G7"