#%RAML 1.0 NamedExample
value:
  -
    PutnikID: 1
    Ime: "Gojko"
    Prezime: "Zemunac"
    BrojTel: "0695548874"
    EMail: "gojkomunzekonza@gmail.com"
    Godine: 47
    JMBG: "300182957237391"
    prtljag:
      PrtljagID: 1
      RucniPrtljag: false
      Tezina: 19
      PredjenaKontrola: true
      SifraPrtljag: "AEF23"
    pasos:
      PasosID: 1
      Viza: true
      Ime: "Gojko"
      Drzava: "Srbija"
      Prezime: "Zemunac"
      Godine: 47
    karta:
      KartaID: 1
      CenaKarte: 130
      BrojKredKartice: "8398938457684728"
      Klasa: "Economy"
      Sediste: 33
      SifraKarte: "SFT484"
      let:
        LetID: 1
        NazivLinije: "MUNPAR332"
        SifraLeta: "54729232"
        avion:
          AvionID: 1
          Model: "Boing 747"
          BrojLeta: "MUN703"
          PutniciEconomy: 103
          PutniciBusiness: 50
          BrojClanovaPosade: 20
          Vlasnik: "Turkish Airlines"
        poletanje:
          PoletanjeID: 1
          Grad: "Minhen"
          Datum: "30-05-2023"
          Gate: "L7"
        sletanje:
          SletanjeID: 1
          Grad: "Paris"
          Datum: "30-05-2023"
          Gate: "G7"
  
  -
    PutnikID: 2
    Ime: "Sofronije"
    Prezime: "Aziv"
    BrojTel: "06348593923"
    EMail: "azivkralj@gmail.com"
    Godine: 32
    JMBG: "20194123498345"
    prtljag:
      PrtljagID: 2
      RucniPrtljag: false
      Tezina: 18
      PredjenaKontrola: true
      SifraPrtljag: "GEF87"
    pasos:
      PasosID: 2
      Viza: false
      Ime: "Sofronije"
      Drzava: "Bugarska"
      Prezime: "Aziv"
      Godine: 32
    karta:
      KartaID: 2
      CenaKarte: 340
      BrojKredKartice: "1432960580674768"
      Klasa: "Business"
      Sediste: 2
      SifraKarte: "BTR132"
      let:
        LetID: 2
        NazivLinije: "BERBUD602"
        SifraLeta: "48237843"
        avion:
          AvionID: 2
          Model: "Boing 737"
          BrojLeta: "BER533"
          PutniciEconomy: 123
          PutniciBusiness: 47
          BrojClanovaPosade: 22
          Vlasnik: "Etihad Airlines"
        poletanje:
          PoletanjeID: 2
          Grad: "Berlin"
          Datum: "30-05-2023"
          Gate: "P3"
        sletanje:
          SletanjeID: 2
          Grad: "Budapest"
          Datum: "30-05-2023"
          Gate: "N2"
