#%RAML 1.0 NamedExample
value:
  -
    KartaID: 1
    CenaKarte: 130
    BrojKredKartice: "8398938457684728"
    Klasa: "Economy"
    Sediste: 33
    SifraKarte: "SFT484"
    let:
      LetID: 1
      NazivLinije: "MUNPAR332"
      SifraLeta: "54729232"
      avion:
        AvionID: 1
        Model: "Boing 747"
        BrojLeta: "MUN703"
        PutniciEconomy: 103
        PutniciBusiness: 50
        BrojClanovaPosade: 20
        Vlasnik: "Turkish Airlines"
      poletanje:
        PoletanjeID: 1
        Grad: "Minhen"
        Datum: "30-05-2023"
        Gate: "L7"
      sletanje:
        SletanjeID: 1
        Grad: "Paris"
        Datum: "30-05-2023"
        Gate: "G7"
  -
    KartaID: 2
    CenaKarte: 340
    BrojKredKartice: "1432960580674768"
    Klasa: "Business"
    Sediste: 2
    SifraKarte: "BTR132"
    let:
      LetID: 2
      NazivLinije: "BERBUD602"
      SifraLeta: "48237843"
      avion:
        AvionID: 2
        Model: "Boing 737"
        BrojLeta: "BER533"
        PutniciEconomy: 123
        PutniciBusiness: 47
        BrojClanovaPosade: 22
        Vlasnik: "Etihad Airlines"
      poletanje:
        PoletanjeID: 2
        Grad: "Berlin"
        Datum: "30-05-2023"
        Gate: "P3"
      sletanje:
        SletanjeID: 2
        Grad: "Budapest"
        Datum: "30-05-2023"
        Gate: "N2"
