#%RAML 1.0 NamedExample
value:
    NazivLinije: "MUNPAR332"
    SifraLeta: "54729232"
    avion:
      AvionID: 1
      Model: "Boing 747"
      BrojLeta: "MUN703"
      PutniciEconomy: 103
      PutniciBusiness: 50
      BrojClanovaPosade: 20
      Vlasnik: "Turkish Airlines"
    poletanje:
      PoletanjeID: 1
      Grad: "Minhen"
      Datum: "30-05-2023"
      Gate: "L7"
    sletanje:
      SletanjeID: 1
      Grad: "Paris"
      Datum: "30-05-2023"
      Gate: "G7"